language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
    - npm install -g vuepress

script:
    - npm run docs:build
    
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  local-dir: docs/.vuepress/dist
  on:
    branch: master